kind: Service
apiVersion: v1
metadata:
  name: ejpk-external-load-balancer
spec:
  ports:
      port: 443
      targetPort: 80
  selector:
    app: ejpk-licence-signatures
    tier: frontend
  type: LoadBalancer