kind: Service
apiVersion: v1
metadata:
  name: ejpk-external-load-balancer
spec:
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 5000

  selector:
    app: ejpk-licence-signatures
    tier: frontend
  type: LoadBalancer