kind: Service
apiVersion: v1
metadata:
  name: ejpk-internal-load-balancer-frontend
spec:
  ports:
    - protocol: TCP
      targetPort: 5000
  selector:
    app: ejpk-licence-signatures
    tier: frontend
  type: LoadBalancer