apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejpk-request-router
spec:
  selector:
    matchLabels:
      app: ejpk-licence-signatures
      name: ejpk-router
  replicas: 2
  template:
    metadata:
      labels:
        app: ejpk-licence-signatures
        tier: frontend
        name: ejpk-router
    spec:
      containers:
        - name: router
          image: lsa77/ejpk-router
          ports:
            - containerPort: 80
        env:
          - name: SIGNER_URL
            vaue: http://ejpk-internal-load-balancer-frontend.default.svc.cluster.local:80
