kind: Service
apiVersion: v1
metadata:
  name: ejpk-backend-signer-service
type: ClusterIP
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: ejpk-licence-signers
    tier: backend