kind: Service
apiVersion: v1
metadata:
  name: ejpk-backend-signer-service

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: ClusterIP
  selector:
    app: ejpk-licence-signers
    tier: backend